# Generated by Django 5.2.6 on 2025-09-10 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='название книги')),
                ('author', models.CharField(max_length=100, verbose_name='автор')),
                ('description', models.TextField(verbose_name='описание')),
                ('publish_date', models.DateField(verbose_name='дата публикации')),
                ('pages', models.IntegerField(verbose_name='количество страниц')),
                ('cover', models.ImageField(upload_to='books/', verbose_name='обложка')),
                ('genre', models.CharField(choices=[('роман', 'роман'), ('фантастика', 'фантастика'), ('фэнтези', 'фэнтези'), ('нон фикшн', 'нон фикшн'), ('детектив', 'детектив')], default='роман', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='цена')),
                ('language', models.CharField(max_length=50, verbose_name='язык')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
    ]
