# Generated by Django 5.2.6 on 2025-09-16 12:09

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone_number', models.CharField(default='+996', max_length=14)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('М', 'М'), ('Ж', 'Ж')], max_length=100)),
                ('education_level', models.CharField(blank=True, choices=[('hs', 'среднее'), ('ba', 'высшее'), ('ms', 'магистратура'), ('phd', 'докторантура')], max_length=20, null=True)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('desired_position', models.CharField(blank=True, max_length=100, null=True)),
                ('skills', models.TextField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
