# Generated by Django 5.2.6 on 2025-09-18 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'кандидат', 'verbose_name_plural': 'кандидаты'},
        ),
    ]
